"""Default bilingual copy and per-field limits used by the public site and admin."""

DEFAULT_SITE_TEXTS = [
    # section, key, admin label, English, Persian, maximum characters
    ("navigation", "navHome", "Home menu", "HOME", "خانه", 20),
    ("navigation", "navWork", "Work menu", "WORK", "نمونه‌کارها", 20),
    ("navigation", "navAbout", "About menu", "ABOUT", "درباره من", 20),
    ("navigation", "navServices", "Services menu", "SERVICES", "خدمات", 20),
    ("navigation", "navContact", "Contact menu", "CONTACT", "تماس", 20),
    ("hero", "heroKicker", "Eyebrow", "MOTION DESIGNER / FILM EDITOR", "طراح موشن / تدوینگر فیلم", 55),
    ("hero", "heroTitleOne", "Title — line 1", "MOTION", "موشن", 22),
    ("hero", "heroTitleTwo", "Title — line 2", "MADE TO", "ساخته‌شده", 22),
    ("hero", "heroTitleThree", "Title — line 3", "STAY WITH YOU.", "برای ماندن.", 28),
    ("hero", "heroCopy", "Introduction", "I turn clear ideas into motion, edits and visual systems people remember.", "ایده‌های روشن را به موشن، تدوین و سیستم‌های بصری ماندگار تبدیل می‌کنم.", 180),
    ("hero", "viewWork", "Work button", "VIEW SELECTED WORK", "دیدن نمونه‌کارها", 35),
    ("hero", "startProject", "Contact button", "START A PROJECT", "شروع یک پروژه", 35),
    ("hero", "availability", "Availability", "AVAILABLE FOR SELECT PROJECTS · 2026", "آمادهٔ همکاری برای پروژه‌های منتخب · ۲۰۲۶", 65),
    ("hero", "portraitCaption", "Portrait caption", "BASED IN TEHRAN · WORKING WORLDWIDE", "تهران · همکاری با سراسر جهان", 65),
    ("hero", "selectedWork", "Selected work label", "SELECTED WORK", "نمونه‌کارهای منتخب", 30),
    ("work", "workKicker", "Eyebrow", "SELECTED PROJECTS / 2025—2026", "پروژه‌های منتخب / ۲۰۲۵—۲۰۲۶", 55),
    ("work", "workTitle", "Title", "WORK WITH A POINT OF VIEW.", "کارهایی با نگاه مشخص.", 55),
    ("work", "workCopy", "Introduction", "A focused selection across motion identities, edits, brand films and CGI.", "گزیده‌ای هدفمند از هویت‌های متحرک، تدوین، فیلم برند و CGI.", 180),
    ("work", "filterLabel", "Filter label", "EXPLORE BY DISCIPLINE", "مرور براساس تخصص", 35),
    ("work", "allWork", "All filter", "All work", "همه آثار", 22),
    ("work", "emptyEyebrow", "Empty state label", "01 / FIRST FRAME", "۰۱ / اولین فریم", 35),
    ("work", "emptyTitle", "Empty state title", "READY FOR YOUR WORK.", "آمادهٔ نمایش آثار شما.", 45),
    ("work", "emptyCopy", "Empty state description", "Add a category first, then add a work with its YouTube URL from Studio Control.", "ابتدا دسته‌بندی و سپس نمونه‌کار و لینک یوتیوب آن را در پنل مدیریت ثبت کنید.", 180),
    ("work", "openAdmin", "Admin button", "OPEN ADMIN", "ورود به پنل", 30),
    ("about", "aboutKicker", "Eyebrow", "THE PERSON BEHIND THE FRAMES", "کسی که پشت فریم‌هاست", 55),
    ("about", "aboutTitleOne", "Title — line 1", "TECHNICAL CRAFT.", "مهارت فنی.", 35),
    ("about", "aboutTitleTwo", "Title — line 2", "HUMAN FEELING.", "احساس انسانی.", 35),
    ("about", "aboutCopy", "Introduction", "Technology makes motion possible. Taste makes it worth watching. I combine both to turn a clear strategy into frames people remember.", "تکنولوژی حرکت را ممکن می‌کند؛ سلیقه تماشای آن را ارزشمند می‌کند. این دو را ترکیب می‌کنم تا یک استراتژی روشن به فریم‌هایی ماندگار تبدیل شود.", 280),
    ("about", "aboutStatement", "Creative principle", "Every frame should earn its place — through clarity, rhythm or emotion.", "هر فریم باید جای خودش را با وضوح، ریتم یا احساس به دست بیاورد.", 180),
    ("about", "years", "Years label", "YEARS OF EXPERIENCE", "سال تجربه", 30),
    ("about", "projects", "Projects label", "PROJECTS DELIVERED", "پروژهٔ تحویل‌شده", 30),
    ("about", "countries", "Countries label", "COUNTRIES REACHED", "کشور", 30),
    ("services", "servicesKicker", "Eyebrow", "WHAT I CAN BUILD FOR YOU", "چیزی که برای شما می‌سازم", 55),
    ("services", "servicesTitle", "Title", "FROM FIRST IDEA TO FINAL FRAME.", "از اولین ایده تا آخرین فریم.", 65),
    ("services", "servicesCopy", "Introduction", "One clear creative route, shaped around the message and finished with care.", "یک مسیر خلاق روشن، متناسب با پیام شما و اجراشده با دقت.", 180),
    ("services", "motionDesign", "Motion title", "MOTION DESIGN", "طراحی موشن", 35),
    ("services", "motionDescription", "Motion description", "Motion identities, title sequences and campaign systems built to hold attention.", "هویت متحرک، تیتراژ و سیستم‌های کمپین برای جلب و حفظ توجه.", 180),
    ("services", "motionDeliverables", "Motion deliverables", "IDENTITY · TITLES · CAMPAIGNS", "هویت · تیتراژ · کمپین", 55),
    ("services", "filmEditing", "Editing title", "FILM EDITING", "تدوین فیلم", 35),
    ("services", "editDescription", "Editing description", "Story, pacing and sound brought together in one deliberate editorial rhythm.", "ترکیب داستان، ریتم و صدا در یک تدوین دقیق و هدفمند.", 180),
    ("services", "editDeliverables", "Editing deliverables", "STORY · RHYTHM · SOUND", "داستان · ریتم · صدا", 55),
    ("services", "artDirection", "Art direction title", "ART DIRECTION", "هدایت هنری", 35),
    ("services", "artDescription", "Art direction description", "A distinct visual language that stays coherent from concept to delivery.", "یک زبان بصری متمایز و منسجم، از ایده تا خروجی نهایی.", 180),
    ("services", "artDeliverables", "Art direction deliverables", "CONCEPT · STYLE · SYSTEM", "ایده · استایل · سیستم", 55),
    ("services", "cgi", "CGI title", "CGI / 3D", "سه‌بعدی و CGI", 35),
    ("services", "cgiDescription", "CGI description", "Purposeful digital worlds and product visuals with convincing material detail.", "دنیاها و تصاویر محصول با جزئیات متریال باورپذیر و هدفمند.", 180),
    ("services", "cgiDeliverables", "CGI deliverables", "WORLDS · PRODUCT · SIMULATION", "دنیا · محصول · شبیه‌سازی", 55),
    ("contact", "contactKicker", "Eyebrow", "YOUR MOVE", "حرکت بعدی با شماست", 35),
    ("contact", "contactTitleOne", "Title — line 1", "LET’S MAKE", "بیایید چیزی", 35),
    ("contact", "contactTitleTwo", "Title — line 2", "SOMETHING MATTER.", "اثرگذار بسازیم.", 40),
    ("contact", "contactCopy", "Introduction", "Share the goal, timeline and scope. I’ll reply with a clear creative route.", "هدف، زمان‌بندی و محدودهٔ پروژه را بفرستید؛ با یک مسیر خلاق روشن پاسخ می‌دهم.", 200),
    ("contact", "nameLabel", "Name field", "NAME", "نام", 25),
    ("contact", "emailLabel", "Email field", "EMAIL", "ایمیل", 25),
    ("contact", "companyLabel", "Company field", "COMPANY", "شرکت", 25),
    ("contact", "serviceLabel", "Service field", "SERVICE", "خدمت", 25),
    ("contact", "chooseService", "Service placeholder", "Choose service", "انتخاب خدمت", 35),
    ("contact", "other", "Other service", "Something else", "یک کار متفاوت", 35),
    ("contact", "messageLabel", "Brief field", "PROJECT BRIEF", "بریف پروژه", 30),
    ("contact", "sendBrief", "Submit button", "SEND THE BRIEF", "ارسال بریف", 35),
    ("contact", "sending", "Sending state", "SENDING…", "در حال ارسال…", 35),
    ("contact", "formSuccess", "Success message", "BRIEF RECEIVED. I’LL REPLY SHORTLY.", "بریف دریافت شد؛ به‌زودی پاسخ می‌دهم.", 100),
    ("contact", "formError", "Error message", "Please check the highlighted fields.", "لطفاً فیلدهای مشخص‌شده را بررسی کنید.", 100),
]


DEFAULT_SITE_TEXT_MAP = {
    key: {"en": text_en, "fa": text_fa}
    for _section, key, _label, text_en, text_fa, _limit in DEFAULT_SITE_TEXTS
}
